Feature/main feature
pacyL2K19/restaurant-app pull request #3
Opened 2021-05-14 20:59 UTC by pacyL2K19

# The aim of this PR 
- Creation of js files to manipulate the DOM 
- Add images to the project 
- Add multiple page and links between them

2021-05-16 16:44 UTC, Forison requested changes
## Invalid Request❕❓

#### Please not that, you have to make sure all linter checks are passing before you submit a review request, this P/R is therefore marked invalid🤗.

#### Kindly address the failing checks and submit a re-review.

#### Happy coding

Addo Forison

2021-05-16 23:18 UTC, Forison requested changes
# Status::Change required☑️ 

#### Good job on addressing the failing checks. Your pull request, commit messages and readme are are professional. Your code is split into module as required The page looks great.
Here is one thing to do to get this approved.
* [ ]  It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Kindly go ahead and merge the branch and proceed the next milestone💪.

#### Happy coding👨‍💻

Addo Forison

2021-05-16 23:18 UTC, Forison commented on dist/index.html
> +    <!-- <link rel="shortcut icon" href="./images/favicon.ico" /> -->
Always remove commented code.

2021-05-17 09:50 UTC, pacyL2K19 commented on dist/index.html
> +    <!-- <link rel="shortcut icon" href="./images/favicon.ico" /> -->
Thank you, done

2021-05-17 09:58 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED✔✔✔**

Hello @pacyL2K19 
Great work making the requested changes.

You can merge👏👏

Happy coding💻💻💻

2021-05-17 10:00 UTC, pacyL2K19 commented
Thank you for the review @NtwaliHeritier

2021-05-17 10:00 UTC, merged